#!/usr/bin/env bash
#A bash script that displays Best School 10 times but for the 9th iteration, displays Best School and the HI on a new line
x=1
while ((x <= 10))
do
  if ((x == 9))
  then
	  echo "Best School"
          echo "Hi"
  else
	   echo "Best School"
  fi
  x=$((x + 1))
done
