#!/usr/bin/env bash
#A bash script that displays time for 12hours and 59 minutes
x=0
while ((x <= 12))
do
   echo "Hour: $x"
   m=1
   while ((m <= 59))
   do
      echo "$m"
   m=$((m + 1))
   done
   x=$((x + 1))
done
