#!/usr/bin/env bash
# Create my pid script, assign a message for some signals

echo "$$" > /var/run/myscript.pid

while true; do
	echo "To infinty and beyond"
	# trap SIGTERM signal
	trap "echo 'I hate the kill command'; rm /var/run/myscript.pid" SIGTERM
	trap "echo 'Y U no love me?!'; rm /var/run/myscript.pid" SIGINT
done

