#!/usr/bin/env bash
# Init script to manage another process

# Start my process
start() {
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
}

stop() {
	#kill manage_my_process
	pkill -f ./manage_my_process
	rm /var/run/my_process.pid
}

case "$1" in
	start)
		start
		echo "manage_my_process started"
		;;
	stop)
		stop
		echo "manage_my_process stopped"
		;;
	restart)
		stop
		start
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac

